---
abstract: 'Create HTML version of OTRS documentation'
author:
  - 'Renee Bäcker <module@renee-baecker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EPublisher-Target-Plugin-OTRSDoc
requires:
  EPublisher: 0.6
  File::Basename: 2
  File::Path: 2.08
  HTML::Template::Compiled: 0
  Pod::Simple::XHTML: 3.14
version: 0.1
